# -*- coding: utf-8 -*-
"""
DataMate 算子注册 SQL 生成脚本。

该脚本读取 operators 目录下的元数据并生成幂等注册语句。
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def sql_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sql_value(value: str) -> str:
    if value == "":
        return "NULL"
    if value.lower() in {"t", "true"}:
        return "TRUE"
    if value.lower() in {"f", "false"}:
        return "FALSE"
    return "'" + value.replace("'", "''") + "'"


def read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        return list(reader.fieldnames or []), list(reader)


def insert_sql(table: str, columns: list[str], row: dict[str, str], conflict_columns: list[str]) -> str:
    col_sql = ", ".join(sql_ident(col) for col in columns)
    val_sql = ", ".join(sql_value(row.get(col, "")) for col in columns)
    update_columns = [col for col in columns if col not in conflict_columns]
    conflict_sql = ", ".join(sql_ident(col) for col in conflict_columns)
    if update_columns:
        update_sql = ", ".join(f"{sql_ident(col)} = EXCLUDED.{sql_ident(col)}" for col in update_columns)
        action = f"DO UPDATE SET {update_sql}"
    else:
        action = "DO NOTHING"
    return f"INSERT INTO {sql_ident(table)} ({col_sql}) VALUES ({val_sql}) ON CONFLICT ({conflict_sql}) {action};"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--export-dir",
        default="release_assets/datamate_state/20260621T114504Z",
        help="Directory containing t_operator_ccf.csv and t_operator_category_relation_ccf.csv.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output SQL path. Defaults to <export-dir>/datamate_operator_registration.sql.",
    )
    args = parser.parse_args()

    export_dir = (ROOT / args.export_dir).resolve() if not Path(args.export_dir).is_absolute() else Path(args.export_dir)
    output = Path(args.output) if args.output else export_dir / "datamate_operator_registration.sql"
    output = output.resolve()

    operator_csv = export_dir / "t_operator_ccf.csv"
    relation_csv = export_dir / "t_operator_category_relation_ccf.csv"
    if not operator_csv.exists():
        raise FileNotFoundError(operator_csv)
    if not relation_csv.exists():
        raise FileNotFoundError(relation_csv)

    op_columns, op_rows = read_csv(operator_csv)
    rel_columns, rel_rows = read_csv(relation_csv)

    lines = [
        "-- Generated by scripts/generate_datamate_registration_sql.py",
        "-- Review before applying to a clean DataMate database.",
        "-- This script is idempotent for t_operator.id and t_operator_category_relation(category_id, operator_id).",
        "BEGIN;",
        "",
        "-- Medical AI custom operators",
    ]
    for row in op_rows:
        lines.append(insert_sql("t_operator", op_columns, row, ["id"]))
    lines.extend(["", "-- CCF operator category relations"])
    for row in rel_rows:
        lines.append(insert_sql("t_operator_category_relation", rel_columns, row, ["category_id", "operator_id"]))
    lines.extend(["", "COMMIT;", ""])

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated SQL: {output}")
    print(f"operators: {len(op_rows)}")
    print(f"category_relations: {len(rel_rows)}")


if __name__ == "__main__":
    main()
